server:
  address: 0.0.0.0:8080

postgres:
  address: postgres:5432
  user: cluer
  password: ""
  dbname: cluer
  sslmode: disable

logger:
  default:
    level: info
  modules:
    server:
      level: debug